// eslint-disable-next-line to ignore the next line.
/* eslint-disable */ 
export const MEIGARA_NUM = 'MEIGARA_NUM'
export const TODAY = 'TODAY'
export const DIF = 'DIF'
export const C_NAME = 'C_NAME'
export const SIGVAL = 'SIGVAL'
export const EPS = 'EPS'
export const TENKAN = 'TENKAN'
export const CONFVAL = 'CONFVAL'
export const KAGENCHI = 'KAGENCHI'
export const COEFF = 'KOEFF'
export const STA = 'STA'
export const AR = 'AR'
export const SAR = 'SAR'
